# Generated by Django 6.0 on 2025-12-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(choices=[('#15', '#15 Small'), ('#22', '#22 Medium'), ('#25', '#25 Large'), ('7X12', '7X12 White'), ('9X15', '9X15 White')], max_length=20)),
                ('color', models.CharField(choices=[('White', 'White'), ('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue')], max_length=20)),
                ('gsm', models.IntegerField(choices=[(40, '40 GSM'), (60, '60 GSM'), (80, '80 GSM'), (100, '100 GSM')], verbose_name='GSM Thickness')),
                ('quantity_bales', models.IntegerField(default=0, verbose_name='Stock Quantity (Bales)')),
                ('location', models.CharField(default='Athiriver Warehouse', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
